Correct spelling error in login
shukon/BDP pull request #16
Opened 2020-01-02 21:27 UTC by GerJuli

2020-01-04 10:55 UTC, shukon commented
Sollten wir an dieser Stelle vielleicht direkt die Fehlermeldung informativer gestalten? So dass die Aussage tatsächlich stimmt? :)

2020-01-04 12:03 UTC, GerJuli commented
Ich habe das mal versucht :) Der Loginprozess ist jetzt zweigeteilt siehe commit message

2020-01-04 15:53 UTC, shukon requested changes

2020-01-04 15:53 UTC, shukon commented on bdp_app/lib/pages/LoginPage.dart
> +		title: new Text("Benutztername falsch"));
Da ist ein typo: Benutzername statt Benutz**t**ername

2020-01-04 15:53 UTC, shukon commented on bdp_app/lib/pages/LoginPage.dart
> +		    title: new Text("Psswort falsch"));
Wenn schon so speziell, dann richtig: "Passwort", da fehlt ein a :)

2020-01-04 15:55 UTC, GerJuli commented on bdp_app/lib/pages/LoginPage.dart
> +		title: new Text("Benutztername falsch"));
Ich habe gedacht das gehört so weil Benutzername generisch maskulin ist

2020-01-04 15:55 UTC, GerJuli commented on bdp_app/lib/pages/LoginPage.dart
> +		    title: new Text("Psswort falsch"));
Oh ja vielen Dank!

2020-01-07 15:23 UTC, shukon commented on bdp_app/lib/pages/LoginPage.dart
> +		title: new Text("Benutztername falsch"));
Achso. Ja ok :)

2020-01-07 15:24 UTC, merged